import { Itinerary } from './tools';

export const itineraries: Itinerary[] = [
  {
    id: 1,
    title: 'Caribbean Explorer',
    description:
      'Explore the beautiful islands of the Caribbean on this 7-day cruise.',
    price: 999,
    duration: '7 days',
    departureDate: '2024-01-15',
    returnDate: '2024-01-22',
    departurePort: 'Miami, FL',
    arrivalPort: 'Miami, FL',
    portsOfCall: [
      'Nassau, Bahamas',
      'Cozumel, Mexico',
      'George Town, Cayman Islands',
    ],
    imageUrl: 'https://www.shutterstock.com/image-photo/aerialview-generic-cruise-ship-traveling-260nw-2388232903.jpg',
    shipName: 'SS Caribbean',
    amenities: ['Pool', 'Spa', 'Casino', 'Theater'],
  },
  {
    id: 2,
    title: 'Mediterranean Odyssey',
    description:
      'Discover ancient civilizations and stunning coastlines in the Mediterranean.',
    price: 1299,
    duration: '10 days',
    departureDate: '2024-04-10',
    returnDate: '2024-04-20',
    departurePort: 'Barcelona, Spain',
    arrivalPort: 'Venice, Italy',
    portsOfCall: ['Marseille, France', 'Rome, Italy', 'Athens, Greece'],
    imageUrl: 'https://www.shutterstock.com/image-photo/aerialview-generic-cruise-ship-traveling-260nw-2388232903.jpg',
    shipName: 'MS Odyssey',
    amenities: ['Fine Dining', 'Wine Tasting', 'Art Gallery'],
  },
  {
    id: 3,
    title: 'Alaskan Adventure',
    description:
      "Experience the rugged beauty of Alaska's glaciers and wildlife.",
    price: 1499,
    duration: '7 days',
    departureDate: '2024-06-05',
    returnDate: '2024-06-12',
    departurePort: 'Seattle, WA',
    arrivalPort: 'Anchorage, AK',
    portsOfCall: ['Juneau, AK', 'Skagway, AK', 'Ketchikan, AK'],
    imageUrl: 'https://www.shutterstock.com/image-photo/aerialview-generic-cruise-ship-traveling-260nw-2388232903.jpg',
    shipName: 'MV Glacier',
    amenities: ['Helicopter Tours', 'Wildlife Watching', 'Onboard Lectures'],
  },
  {
    id: 4,
    title: 'Northern Lights Cruise',
    description: 'Chase the Aurora Borealis across the Arctic Circle.',
    price: 1799,
    duration: '12 days',
    departureDate: '2024-09-01',
    returnDate: '2024-09-13',
    departurePort: 'Reykjavik, Iceland',
    arrivalPort: 'Tromsø, Norway',
    portsOfCall: [
      'Akureyri, Iceland',
      'Lofoten Islands, Norway',
      'Alta, Norway',
    ],
    imageUrl: 'https://www.shutterstock.com/image-photo/aerialview-generic-cruise-ship-traveling-260nw-2388232903.jpg',
    shipName: 'MS Aurora',
    amenities: ['Observation Deck', 'Hot Springs', 'Photography Workshops'],
  },
  {
    id: 5,
    title: 'Asian Discovery',
    description: 'Immerse yourself in the rich cultures of East Asia.',
    price: 1399,
    duration: '10 days',
    departureDate: '2024-03-15',
    returnDate: '2024-03-25',
    departurePort: 'Tokyo, Japan',
    arrivalPort: 'Shanghai, China',
    portsOfCall: ['Osaka, Japan', 'Seoul, South Korea', 'Hong Kong'],
    imageUrl: 'https://www.shutterstock.com/image-photo/aerialview-generic-cruise-ship-traveling-260nw-2388232903.jpg',
    shipName: 'SS Orient',
    amenities: ['Cultural Shows', 'Cooking Classes', 'Language Workshops'],
  },
  {
    id: 6,
    title: 'South Pacific Sojourn',
    description: 'Relax in the idyllic islands of the South Pacific.',
    price: 1599,
    duration: '8 days',
    departureDate: '2024-05-20',
    returnDate: '2024-05-28',
    departurePort: 'Sydney, Australia',
    arrivalPort: 'Auckland, New Zealand',
    portsOfCall: ['Nouméa, New Caledonia', 'Port Vila, Vanuatu', 'Suva, Fiji'],
    imageUrl: 'https://www.shutterstock.com/image-photo/aerialview-generic-cruise-ship-traveling-260nw-2388232903.jpg',
    shipName: 'MV Paradise',
    amenities: ['Beach Excursions', 'Water Sports', 'Island BBQ'],
  },
  {
    id: 7,
    title: 'Transatlantic Crossing',
    description: 'Experience the classic journey across the Atlantic Ocean.',
    price: 1099,
    duration: '7 days',
    departureDate: '2024-07-10',
    returnDate: '2024-07-17',
    departurePort: 'New York, NY',
    arrivalPort: 'Southampton, UK',
    portsOfCall: ['At Sea'],
    imageUrl: 'https://www.shutterstock.com/image-photo/aerialview-generic-cruise-ship-traveling-260nw-2388232903.jpg',
    shipName: 'SS Atlantic',
    amenities: ['Gala Nights', 'Ballroom Dancing', 'Lectures'],
  },
  {
    id: 8,
    title: 'Antarctic Expedition',
    description: 'Explore the pristine wilderness of Antarctica.',
    price: 2999,
    duration: '14 days',
    departureDate: '2024-12-01',
    returnDate: '2024-12-15',
    departurePort: 'Ushuaia, Argentina',
    arrivalPort: 'Ushuaia, Argentina',
    portsOfCall: ['Antarctic Peninsula', 'South Shetland Islands'],
    imageUrl: 'https://www.shutterstock.com/image-photo/aerialview-generic-cruise-ship-traveling-260nw-2388232903.jpg',
    shipName: 'MV Explorer',
    amenities: [
      'Zodiac Excursions',
      'Scientific Lectures',
      'Photography Tours',
    ],
  },
  {
    id: 9,
    title: 'Baltic Capitals',
    description: 'Visit the historic capitals along the Baltic Sea.',
    price: 1299,
    duration: '9 days',
    departureDate: '2024-08-05',
    returnDate: '2024-08-14',
    departurePort: 'Copenhagen, Denmark',
    arrivalPort: 'Stockholm, Sweden',
    portsOfCall: [
      'Tallinn, Estonia',
      'St. Petersburg, Russia',
      'Helsinki, Finland',
    ],
    imageUrl: 'https://www.shutterstock.com/image-photo/aerialview-generic-cruise-ship-traveling-260nw-2388232903.jpg',
    shipName: 'MS Baltic',
    amenities: ['City Tours', 'Historical Lectures', 'Local Cuisine'],
  },
  {
    id: 10,
    title: 'Amazon River Cruise',
    description: 'Journey deep into the heart of the Amazon rainforest.',
    price: 1899,
    duration: '11 days',
    departureDate: '2024-11-10',
    returnDate: '2024-11-21',
    departurePort: 'Manaus, Brazil',
    arrivalPort: 'Belém, Brazil',
    portsOfCall: ['Parintins, Brazil', 'Santarem, Brazil', 'Macapá, Brazil'],
    imageUrl: 'https://www.shutterstock.com/image-photo/aerialview-generic-cruise-ship-traveling-260nw-2388232903.jpg',
    shipName: 'MV Amazonia',
    amenities: [
      'Wildlife Expeditions',
      'Cultural Visits',
      'Onboard Naturalists',
    ],
  },
];
